server:
  port: 8082

spring:
  application:
    name: chat
  data:
    mongodb:
      uri: mongodb://localhost:27017/carrotTestDB
  kafka:
    consumer:
      group-id: chat
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true